alter table chat_messages drop foreign key FKgiqeap8ays4lf684x7m0r2729;
alter table chat_messages drop foreign key FKr8do0njvs3jw1lat7qee7q83c;
alter table customers drop foreign key FKrh1g1a20omjmn6kurd35o3eit;
alter table items drop foreign key FKqh50thk0y39r89lr8vmkhreyx;
alter table shoppers drop foreign key FKd1703f2y4ot64y5nnnrfrfp1v;
alter table shopping_requests drop foreign key FKp5ykskmj6ywwbvd2adxbjvr1o;
alter table shopping_requests drop foreign key FKb90eexgeu3f8xf55nkgr42y3o;
alter table tokens drop foreign key FK2dylsfo39lgjyqml2tbe0b0ss;
drop table if exists chat_message_id_seq;
drop table if exists chat_messages;
drop table if exists customer_id_seq;
drop table if exists customers;
drop table if exists item_id_seq;
drop table if exists items;
drop table if exists payment_id_seq;
drop table if exists payments;
drop table if exists shopper_id_seq;
drop table if exists shoppers;
drop table if exists shopping_request_id_seq;
drop table if exists shopping_requests;
drop table if exists token_sequence;
drop table if exists tokens;
drop table if exists user_id_seq;
drop table if exists users;
create table chat_message_id_seq (next_val bigint) engine=InnoDB;
insert into chat_message_id_seq values ( 1 );
create table chat_messages (id bigint not null, sender_id bigint not null, shopping_request_id bigint not null, timestamp datetime(6) not null, message_content varchar(1000) not null, primary key (id)) engine=InnoDB;
create table customer_id_seq (next_val bigint) engine=InnoDB;
insert into customer_id_seq values ( 1 );
create table customers (id bigint not null, user_id bigint not null, address varchar(500), primary key (id)) engine=InnoDB;
create table item_id_seq (next_val bigint) engine=InnoDB;
insert into item_id_seq values ( 1 );
create table items (amount integer not null check (amount>=1), id bigint not null, shopping_request_id bigint not null, category varchar(50), name varchar(100) not null, description varchar(500), primary key (id)) engine=InnoDB;
create table payment_id_seq (next_val bigint) engine=InnoDB;
insert into payment_id_seq values ( 1 );
create table payments (amount decimal(10,2), collected_timestamp datetime(6), created_timestamp datetime(6) not null, customer_id bigint not null, id bigint not null, shopping_request_id bigint not null, stripe_client_secret varchar(255), stripe_payment_intent_id varchar(255), status enum ('AUTHORIZED','CANCELLED','COMPLETED','FAILED','PENDING','REFUNDED') not null, primary key (id)) engine=InnoDB;
create table shopper_id_seq (next_val bigint) engine=InnoDB;
insert into shopper_id_seq values ( 1 );
create table shoppers (balance decimal(10,2) not null, id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table shopping_request_id_seq (next_val bigint) engine=InnoDB;
insert into shopping_request_id_seq values ( 1 );
create table shopping_requests (delivery_fee float(53) not null, estimated_items_price float(53) not null, latitude float(53), longitude float(53), store_latitude float(53), store_longitude float(53), created_at datetime(6) not null, customer_id bigint not null, id bigint not null, shopper_id bigint, updated_at datetime(6), store_name varchar(200) not null, delivery_address varchar(500) not null, store_address varchar(500) not null, payment_status enum ('AUTHORIZED','CANCELLED','COMPLETED','FAILED','PENDING','REFUNDED'), status enum ('ACCEPTED','CANCELLED','COMPLETED','IN_PROGRESS','PENDING') not null, primary key (id)) engine=InnoDB;
create table token_sequence (next_val bigint) engine=InnoDB;
insert into token_sequence values ( 1 );
create table tokens (confirmed_at datetime(6), created_at datetime(6) not null, expires_at datetime(6) not null, id bigint not null, user_id bigint not null, token varchar(500) not null, primary key (id)) engine=InnoDB;
create table user_id_seq (next_val bigint) engine=InnoDB;
insert into user_id_seq values ( 1 );
create table users (is_enabled bit not null, is_locked bit not null, created_at datetime(6) not null, id bigint not null, last_password_change datetime(6), updated_at datetime(6), first_name varchar(50) not null, last_name varchar(50) not null, email varchar(100) not null, password_hash varchar(255) not null, phone_number varchar(255) not null, role enum ('CUSTOMER','SHOPPER') not null, primary key (id)) engine=InnoDB;
alter table customers add constraint UKeuat1oase6eqv195jvb71a93s unique (user_id);
alter table shoppers add constraint UKjnhjfj2aaswklo1at3eujar5f unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK9q63snka3mdh91as4io72espi unique (phone_number);
alter table chat_messages add constraint FKgiqeap8ays4lf684x7m0r2729 foreign key (sender_id) references users (id);
alter table chat_messages add constraint FKr8do0njvs3jw1lat7qee7q83c foreign key (shopping_request_id) references shopping_requests (id);
alter table customers add constraint FKrh1g1a20omjmn6kurd35o3eit foreign key (user_id) references users (id);
alter table items add constraint FKqh50thk0y39r89lr8vmkhreyx foreign key (shopping_request_id) references shopping_requests (id);
alter table shoppers add constraint FKd1703f2y4ot64y5nnnrfrfp1v foreign key (user_id) references users (id);
alter table shopping_requests add constraint FKp5ykskmj6ywwbvd2adxbjvr1o foreign key (customer_id) references customers (id);
alter table shopping_requests add constraint FKb90eexgeu3f8xf55nkgr42y3o foreign key (shopper_id) references shoppers (id);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users (id);
